[tool.poetry]
name = "Storage-Manager"
version = "0.1.0"
description = "Strorage Manager v0.1.0"
authors = ["a-pak <kuivalainenap@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
